name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: OpenCV filter2D test
      id: opencv-filter2d-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: OpenCV filter2D test
        setup-command: pip install -r requirements.txt
        command: python -m pytest
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        OPENCV-FILTER2D-TEST_RESULTS: "${{steps.opencv-filter2d-test.outputs.result}}"
      with:
        runners: opencv-filter2d-test
